
services:
  db_auth:
    image: postgres:17.0-alpine3.20
    container_name: db_auth
    environment:  
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432  
    volumes: 
      - db_auth_vol:/var/lib/postgresql/data
    restart: always
    networks: 
      - microservices-net

networks:
  microservices-net:
    driver: bridge

volumes: 
  db_auth_vol:  
    driver: local
